Feature/intial
energinet-singularity/dlr-mrid pull request #1
Opened 2022-04-06 08:24 UTC by vjsaini75

**Description of your changes**

Category:

- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [ ] I have bumped all relevant version numbers
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my changes if this is needed
- [ ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [ ] I have created/corrected automated tests related to the changes, if possible/necessary
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-04-08 08:52 UTC, CodeWitten commented on Dockerfile
> +COPY requirements.txt .
I think it is bette practice to specify relative path: 
COPY app/requirements.txt /

2022-04-08 08:52 UTC, CodeWitten commented on Dockerfile
> +COPY requirements.txt .
I think it is bette practice to specify relative path: 
COPY app/requirements.txt /

2022-04-08 08:53 UTC, CodeWitten commented on Dockerfile
> +RUN python -m pip install -r requirements.txt
This is the line used in dockerfile template:
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt --no-cache-dir && rm requirements.txt

Could we use to keep aligned with template, ore is there a reasone why you changed it?

2022-04-08 08:53 UTC, CodeWitten commented on Dockerfile
> +RUN python -m pip install -r requirements.txt
This is the line used in dockerfile template:
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt --no-cache-dir && rm requirements.txt

Could we use to keep aligned with template, ore is there a reasone why you changed it?

2022-04-08 08:56 UTC, CodeWitten commented on Dockerfile
> +COPY . /app
i suggest you replace with:

COPY ./app

then later when you run script with CMD you can specify absolute path to script file instead.

2022-04-08 08:56 UTC, CodeWitten commented on Dockerfile
> +COPY . /app
i suggest you replace with:

COPY ./app

then later when you run script with CMD you can specify absolute path to script file instead.

2022-04-08 08:57 UTC, CodeWitten commented on Dockerfile
> +CMD ["python","-u", "main.py"]
use python3 and refer to absolute path for script:

CMD ["python3", "-u", "/app/main.py"]

2022-04-08 08:57 UTC, CodeWitten commented on Dockerfile
> +CMD ["python","-u", "main.py"]
use python3 and refer to absolute path for script:

CMD ["python3", "-u", "/app/main.py"]

2022-04-08 09:07 UTC, CodeWitten commented on README.md
> +This code set is build to expose relation between MRID of AMPs measurments used for DLR with the MRID of Line Segments.
I think we should add something like "the format of the input files can be seen in testdata".
Also we should maybe tell somehow that the files originate from our internal systems, maybe to tell that the code is only applicable to a very specific usecase?

2022-04-08 09:07 UTC, CodeWitten commented on README.md
> +This code set is build to expose relation between MRID of AMPs measurments used for DLR with the MRID of Line Segments.
I think we should add something like "the format of the input files can be seen in testdata".
Also we should maybe tell somehow that the files originate from our internal systems, maybe to tell that the code is only applicable to a very specific usecase?

2022-04-08 09:07 UTC, CodeWitten commented on README.md
> +In our case this file generated from ETS application with heade as below
```suggestion
In our case this file generated from ETS application with heade as below
```
```suggestion
In our case this file generated from ETS application with header as below
```

2022-04-08 09:07 UTC, CodeWitten commented on README.md
> +In our case this file generated from ETS application with heade as below
```suggestion
In our case this file generated from ETS application with heade as below
```
```suggestion
In our case this file generated from ETS application with header as below
```

2022-04-08 09:08 UTC, CodeWitten commented on README.md
> +dlr_mrid_PROD.csv file is read with a given interval in sec. and can be tunned while running container.
```suggestion
dlr_mrid_PROD.csv file is read with a given interval in sec. and can be tunned while running container.
```
```suggestion
dlr_mrid_PROD.csv file is read with a given interval in secound. and can be adjusted while running container.
```

2022-04-08 09:08 UTC, CodeWitten commented on README.md
> +dlr_mrid_PROD.csv file is read with a given interval in sec. and can be tunned while running container.
```suggestion
dlr_mrid_PROD.csv file is read with a given interval in sec. and can be tunned while running container.
```
```suggestion
dlr_mrid_PROD.csv file is read with a given interval in secound. and can be adjusted while running container.
```

2022-04-08 09:09 UTC, CodeWitten commented on README.md
> +|cycle_time|900|cycle to read .csv file|
```suggestion
|cycle_time|900|cycle to read .csv file|
```
```suggestion
|cycle_time|900|cycletime for reading csv-file|
```

2022-04-08 09:09 UTC, CodeWitten commented on README.md
> +|cycle_time|900|cycle to read .csv file|
```suggestion
|cycle_time|900|cycle to read .csv file|
```
```suggestion
|cycle_time|900|cycletime for reading csv-file|
```

2022-04-08 09:10 UTC, CodeWitten commented on README.md
> +|database_expose|SEG_MEAS_MRID|database name to be query from rest api|
```suggestion
|database_expose|SEG_MEAS_MRID|database name to be query from rest api|
```
```suggestion
|database_expose|SEG_MEAS_MRID|database name used in query from rest api|
```

2022-04-08 09:10 UTC, CodeWitten commented on README.md
> +|database_expose|SEG_MEAS_MRID|database name to be query from rest api|
```suggestion
|database_expose|SEG_MEAS_MRID|database name to be query from rest api|
```
```suggestion
|database_expose|SEG_MEAS_MRID|database name used in query from rest api|
```

2022-04-08 09:12 UTC, CodeWitten commented on README.md
> +Every cycle_time file define by filename is read. cycle_time should be greter then 10 sec and less then 30 days. otherwise it take defalut value.
```suggestion
The file define by filename is read every cycle_time. The cycle_time should be greater than 10 secounds and less then 30 days, otherwise default value is used. 
```
```suggestion
Every cycle_time file define by filename is read. cycle_time should be greter then 10 sec and less then 30 days. otherwise it take defalut value. 
```

2022-04-08 09:12 UTC, CodeWitten commented on README.md
> +Every cycle_time file define by filename is read. cycle_time should be greter then 10 sec and less then 30 days. otherwise it take defalut value.
```suggestion
The file define by filename is read every cycle_time. The cycle_time should be greater than 10 secounds and less then 30 days, otherwise default value is used. 
```
```suggestion
Every cycle_time file define by filename is read. cycle_time should be greter then 10 sec and less then 30 days. otherwise it take defalut value. 
```

2022-04-08 09:16 UTC, CodeWitten commented on README.md
> +Data exposed via REST API. with database name came be read via
```suggestion
Data exposed via REST API. with database name came be read via
```
```suggestion
Data exposed via REST API. Can be accessed via the shown query:
```

2022-04-08 09:16 UTC, CodeWitten commented on README.md
> +Data exposed via REST API. with database name came be read via
```suggestion
Data exposed via REST API. with database name came be read via
```
```suggestion
Data exposed via REST API. Can be accessed via the shown query:
```

2022-04-08 09:20 UTC, vjsaini75 commented on Dockerfile
> +RUN python -m pip install -r requirements.txt
done

2022-04-08 09:21 UTC, vjsaini75 commented on Dockerfile
> +COPY requirements.txt .
done

2022-04-08 09:26 UTC, CodeWitten commented on README.md
> +docker build dlr_mrid/ -t dlr_mrid:latest
```suggestion
docker build dlr_mrid/ -t dlr_mrid:latest
```
```suggestion
docker build dlr-mrid/ -t dlr-mrid:latest
```

2022-04-08 09:26 UTC, CodeWitten commented on README.md
> +docker build dlr_mrid/ -t dlr_mrid:latest
```suggestion
docker build dlr_mrid/ -t dlr_mrid:latest
```
```suggestion
docker build dlr-mrid/ -t dlr-mrid:latest
```

2022-04-08 09:28 UTC, CodeWitten commented on README.md
> +docker build dlr_mrid/ -t dlr_mrid:latest
Does not work, can't finde requirements file. I think it will work if you follow my corrections suggested to the dockerfile.

2022-04-08 09:28 UTC, CodeWitten commented on README.md
> +docker build dlr_mrid/ -t dlr_mrid:latest
Does not work, can't finde requirements file. I think it will work if you follow my corrections suggested to the dockerfile.

2022-04-08 09:29 UTC, CodeWitten commented on README.md
>  ## Help
write something like: "inital code base" for version numner

2022-04-08 09:29 UTC, CodeWitten commented on README.md
>  ## Help
write something like: "inital code base" for version numner

2022-04-08 09:31 UTC, CodeWitten commented on app/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
this file should only be present in the test folder not also in app folder.

2022-04-08 09:31 UTC, CodeWitten commented on app/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
this file should only be present in the test folder not also in app folder.

2022-04-08 09:57 UTC, CodeWitten commented on tests/test_script.py
>  # Dummytest which will always succeed - must be replaced by real tests
I suggest the test to be rewritten to also check if pandas dataframe is equal to expected outcome based on test input file. You can find inspiration here:
https://github.com/energinet-singularity/conduck/blob/feature/dd20_format_change/tests/test_dd20_parser.py

Or you can just reach out for me, and i will explain more elaborately what i mean.

2022-04-08 10:01 UTC, CodeWitten commented on app/main.py
> +#enviroment varible should be greated then 10 sec and less then 30 days else it get 15 min default
move to inside you main code.

2022-04-08 10:01 UTC, CodeWitten commented on app/main.py
> +#enviroment varible should be greated then 10 sec and less then 30 days else it get 15 min default
move to inside you main code.

2022-04-08 10:02 UTC, CodeWitten commented on app/main.py
> +# if enviroment varible not define database_expose get default database name
move to inside you main code, since else the code will be run on import of you script.

2022-04-08 10:02 UTC, CodeWitten commented on app/main.py
> +# if enviroment varible not define database_expose get default database name
move to inside you main code, since else the code will be run on import of you script.

2022-04-08 10:02 UTC, CodeWitten commented on app/main.py
> +#enviroment varible for filename
move to inside you main code, since else the code will be run on import of you script.

2022-04-08 10:02 UTC, CodeWitten commented on app/main.py
> +#enviroment varible for filename
move to inside you main code, since else the code will be run on import of you script.

2022-04-08 10:03 UTC, CodeWitten commented on app/main.py
> +from singupy import api as singuapi
A general comment. The code will work but i would like it to be rewritten to be more aligned with how python style guides say and also align as a team on how we write code. 

As example look at:
https://github.com/energinet-singularity/singupy/blob/main/singupy/api.py
https://github.com/energinet-singularity/conduck/blob/feature/dd20_format_change/tests/test_dd20_parser.py

You can either look the links for inspiration or call me in for a meeting so i can explain why i would like to change the coding style.

2022-04-08 10:03 UTC, CodeWitten commented on app/main.py
> +from singupy import api as singuapi
A general comment. The code will work but i would like it to be rewritten to be more aligned with how python style guides say and also align as a team on how we write code. 

As example look at:
https://github.com/energinet-singularity/singupy/blob/main/singupy/api.py
https://github.com/energinet-singularity/conduck/blob/feature/dd20_format_change/tests/test_dd20_parser.py

You can either look the links for inspiration or call me in for a meeting so i can explain why i would like to change the coding style.

2022-04-08 10:05 UTC, CodeWitten commented on app/main.py
> +    path1 = "/app/" + str(os.environ.get('file_name'))
i suggest using a more specific name, like "filepath_dlrmrid".

2022-04-08 10:05 UTC, CodeWitten commented on app/main.py
> +    path1 = "/app/" + str(os.environ.get('file_name'))
i suggest using a more specific name, like "filepath_dlrmrid".

2022-04-08 10:06 UTC, CodeWitten commented on app/main.py
> +    if 10 < int(os.environ.get('cycle_time')) < 108720:
what is the reason for restricting the cycle time?

2022-04-08 10:06 UTC, CodeWitten commented on app/main.py
> +    if 10 < int(os.environ.get('cycle_time')) < 108720:
what is the reason for restricting the cycle time?

2022-04-08 10:07 UTC, CodeWitten commented on app/main.py
> +        my_api[database_expose] = clean_file(path1)
i suggest checking if the file has changed since last read and only update date if it has.

2022-04-08 10:07 UTC, CodeWitten commented on app/main.py
> +        my_api[database_expose] = clean_file(path1)
i suggest checking if the file has changed since last read and only update date if it has.

2022-04-08 10:11 UTC, CodeWitten requested changes
Functionality is great, but i would like to align the python code and test more with styleguide and how we code in other repos. You can have a look at my comments, but i also suggest we take a meeting where i explain why i think we should style up your code ;)

2022-04-08 10:12 UTC, vjsaini75 commented on app/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
det er til brug defaut data , i case no file present

2022-04-08 10:14 UTC, vjsaini75 commented on app/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
det er til brug default data , i case no file present

2022-04-08 10:19 UTC, vjsaini75 commented on app/main.py
> +    if 10 < int(os.environ.get('cycle_time')) < 108720:
to avoid user specific error. i don't see and case where user like to re-load file less frequent than 1 month and faster then 10 sec as this is publish on RESTAPI

2022-04-08 10:21 UTC, vjsaini75 commented on app/main.py
> +        my_api[database_expose] = clean_file(path1)
can be done

2022-04-08 10:32 UTC, vjsaini75 commented on app/main.py
> +        my_api[database_expose] = clean_file(path1)
done

2022-04-12 12:07 UTC, swedchef requested changes
Good first shot - especially HELM is not working the the current files. As Anders writes somewhere, the rest will work, but it could be improved to be more standard and similar to the rest of the repo's.

2022-04-12 12:07 UTC, swedchef commented on README.md
> +The file define by filename is read every cycle_time. The cycle_time should be greater than 10 secounds and less then 30 days, otherwise default value is used.
```suggestion
The file define by filename is read every cycle_time. The cycle_time should be greater than 10 secounds and less then 30 days, otherwise default value of 900 seconds is used. 
```

2022-04-12 12:07 UTC, swedchef commented on README.md
> + curl -d '{"sql-query": "SELECT * FROM database_expose;"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
```suggestion
 curl -d '{"sql-query": "SELECT * FROM SEG_MEAS_MRID;"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
```
And then add a comment like "If you changed the 'database_expose' variable, remember to use the correct database name in the curl query".

2022-04-12 13:49 UTC, swedchef approved these changes
I need to GO!

Everything still needs to be fixed - i will hold all of you personally responsible for any- and everything!

2022-04-12 14:07 UTC, vjsaini75 commented on app/main.py
> +
will be with next version

2022-04-12 14:09 UTC, vjsaini75 commented on app/main.py
> +    print("file read time in sec=", cycle_time)
will be next vestion

2022-04-12 14:14 UTC, vjsaini75 commented on app/main.py
> +        cycle_time = 900
this is check if somethis not go as expected , default vaule come up.

2022-04-12 14:14 UTC, vjsaini75 commented on app/main.py
> +        cycle_time = 900
will add log for this

2022-04-13 08:04 UTC, vjsaini75 commented on app/dlr_mrid_PROD.csv
> +Dummy_line,F,12345678-1234-abcd-efgh-123456789def,12345679-4567-ijkl-5678-123456789abc,YES
done with c

2022-04-13 08:33 UTC, vjsaini75 commented on tests/test_script.py
> +        assert True
give issue not same

2022-04-13 10:51 UTC, CodeWitten approved these changes
Maneged to get it up and running in container and query from it :)

I left some comment to be resolved. I also suggest you to use logging instead of print.
Once resolved you can merge.

I think we still need to align on logging, python style and use of mock data in repo. But for now lets's merge it and have a look on how to align with other repos for DLR once you get back from vacation :D

2022-04-13 10:51 UTC, CodeWitten commented on data/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
You should not also put a data folder with dummy file inside the repo. Use instead the file in your test folder. See for example repo "forecast-parser" where test-file is copied via dockerfile and used in code if using mock data is set via flag.

2022-04-13 10:51 UTC, CodeWitten commented on tests/dlr_mrid_PROD.csv
> +TERMINAL_EMSNAME,FAR_NEAR,AMPS_MRID,LINESEGMENT_MRID,DLR_ENABLE
put this file inside a folder and name it "valid-testdata" to align with other repos.

2022-04-13 10:51 UTC, CodeWitten commented on README.md
> +docker run -p 5000:5000 -v docker_volume:/app --rm dlr-mrid:latest
Did not try, but i guess i should be changes since mapping app folder caused issus.

2022-04-13 10:51 UTC, CodeWitten commented on app/main.py
> +        C
your function does not return "C". maybe example is not necceasy here?

2022-04-13 10:51 UTC, CodeWitten commented on app/main.py
> +
remove empty line

2022-04-13 10:51 UTC, CodeWitten commented on app/main.py
> +
remove empty line

2022-04-13 10:51 UTC, CodeWitten commented on app/main.py
> +
remove empty line

2022-04-13 11:51 UTC, merged